WIP - Allow skipping Consul installation
wazo-platform/wazo-ansible pull request #77
Opened 2020-04-09 14:41 UTC by rgarrigue

Consul is an infrastructure tool and may be installed differently than Wazo's way & version. This PR allow skipping its installation.

2020-04-15 12:59 UTC, sduthil commented
This PR will fail in the next step:
```
# need to run after wazo_consul to have wazo_consul_token registered
- name: Set default values
  include_role:
    name: wazo-default
```
This needs consul install, or it will complain about the variable `wazo_consul_token` being unset.

2020-04-15 13:00 UTC, sduthil requested changes
This PR will fail in the next step:
```
# need to run after wazo_consul to have wazo_consul_token registered
- name: Set default values
  include_role:
    name: wazo-default
```
This needs consul install, or it will complain about the variable `wazo_consul_token` being unset.

2020-04-15 14:10 UTC, rgarrigue commented
@sduthil  Well actually it does work. wazo-default does

```yaml
- name: Configure Consul access config
  template:
    src: templates/default_xivo_consul_config.yml.j2
    dest: /var/lib/consul/default_xivo_consul_config.yml
  when: runtime

# be sure to call the wazo_consul role before to have
# wazo_consul_token registered
- name: Configure Consul access token
  template:
    src: templates/default_xivo_consul_token.yml.j2
    dest: /var/lib/consul/default_xivo_consul_token.yml
  when: runtime and wazo_consul_token is defined
```

2nd step is skipped, first step drop a configuration file in a directory irrelevant regarding configuration (it's either /etc/consul/consul.d or /etc/consul.d).

So it's not clean. But it works.

2020-04-16 21:40 UTC, sduthil commented
Sorry for the delay, I don't have much time these days, so I can't search for a better solution. Maybe @fblackburn1 has a better insight?

2020-04-17 12:27 UTC, rgarrigue commented
A cleaner solution ? Easy. Get rid of the homemade Consul setup and rely on the official consul role, https://github.com/ansible-community/ansible-consul. And for each service with a Consul related configuration bit, put that in the given service's role and put it behind a "global" consul_enabled var.

I haven't gone this way because it's quite some work to be done, and I think if we've some time for refactoring we should start by nuking the debian packaging to rely on python package. Which would make ansible's job and Docker's packaging way easier.

2020-04-17 20:07 UTC, fblackburn1 commented
I'm not sure to understand what your *cleaner solution* solve this case

Currently, we only support one embedded consul for the project. If we want to make the consul installation optional, fine, but we must update all related configuration and avoid to have a system with dead/half configuration. If consul is managed externally, then we should consider this installation like if there was no consul. (remove consul symlink, remove wazo-consul-config package, disable all service_discovery configuration, etc..). For this scenario we also need to update some package in our debian packaging

We must not monkey patch our ansible script for specific needed and leave a system half configured with a scenario that we don't community support.

If we want to change our vision about consul and the project, then fine, but we need to discuss about before integrate half solution.

2020-04-29 11:10 UTC, sboily commented
If you make consul optional, you need to disable the discovery feature in services. There is a config to do that on services.

2021-05-26 08:20 UTC, rgarrigue commented
PR is now too old, will open a new one if needed somewhen

2021-05-26 08:20 UTC, closed without merging